### ISSUE TITLE
FDR and P.DE as 0 in the output file for the significant GO pathways

### ISSUE THREAD

**Issue by RKSwamy** [Oshlack/missMethyl#5] opened 2020-08-21 15:46 UTC
When I run the missMethl EPIC code to identify the signficant GO pathways (FDR <0.5), I get an output file with pathways having FDR and P.DE as 0. Is there a P-value cut -off ie if its something insane, it sets it as 0? Or is it a bug. Attached is the output file, the source R script and the run script converted to text files.
[missMEthyl_output.pdf](https://github.com/Oshlack/missMethyl/files/5109737/missMEthyl_output.pdf)
[missMethyl_Runscript.txt](https://github.com/Oshlack/missMethyl/files/5109779/missMethyl_Runscript.txt)
[crystalmethEPIC.txt](https://github.com/Oshlack/missMethyl/files/5109782/crystalmethEPIC.txt)

Many thanks

**Comment by JovMaksimovic** [comment] 2020-09-11 02:32
Hi,
We are aware of this issue. Unfortunately this is a result of output produced by the BiasedUrn package, which is one of our dependencies, so it it not something that we have been able to alter.

**Comment by bphipson** [comment] 2020-09-15 00:17
Hi, 
Would you be able to email me the output from the getMappedEntrezIDs function so I can reproduce the zero p-values? I'm adding a fix to detect exactly zero p-values and run a hypergeometric test instead for those particular gene sets. I suspect it is because the odds are zero for that particular gene set but I would like to confirm it.

Can you also let me know which version of the missMethyl package you are using? We have done a fairly extensive upgrade to the gene set testing functions and I can spot some troublesome categories in your top GO results that are likely false positives if you are using an older version.

**Comment by RKSwamy** [comment] 2020-09-16 21:05
Hello,
Please find attached the output from the getMappedEntrezIDs function.
Many thanks,
Radhika

> getMappedEntrezIDs
function (sig.cpg, all.cpg = NULL, array.type, anno = NULL)
{
    sig.cpg <- as.character(sig.cpg)
    sig.cpg <- sig.cpg[!is.na(sig.cpg)]
    if (is.null(anno)) {
        flat.u <- .getFlatAnnotation(array.type)
    }
    else {
        flat.u <- .getFlatAnnotation(array.type, anno)
    }
    if (is.null(all.cpg))
        all.cpg <- unique(flat.u$cpg)
    else {
        all.cpg <- as.character(all.cpg)
        all.cpg <- all.cpg[!is.na(all.cpg)]
        all.cpg <- unique(all.cpg)
    }
    sig.cpg <- unique(sig.cpg)
    m1 <- match(flat.u$cpg, sig.cpg)
    eg.sig <- flat.u$entrezid[!is.na(m1)]
    eg.sig <- unique(eg.sig)
    m2 <- match(flat.u$cpg, all.cpg)
    eg.all <- flat.u$entrezid[!is.na(m2)]
    freq_genes <- table(eg.all)
    eg.universe <- names(freq_genes)
    test.de <- as.integer(eg.universe %in% eg.sig)
    sorted.eg.sig <- eg.universe[test.de == 1]
    out <- list(sig.eg = sorted.eg.sig, universe = eg.universe,
        freq = freq_genes, de = test.de)
    out
}
<bytecode: 0x91fab1a0>
<environment: namespace:missMethyl>
>

**Comment by bphipson** [comment] 2020-09-23 00:00
Thanks for your bug report, I have committed a fix to avoid p-values of zero.

**Closed as completed by bphipson** 2020-09-23 00:00 UTC
